# 1. Server Configuration
server.port=8080
server.servlet.context-path=/api
spring.application.name=flight-booking-service
# 2. Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/flight_booking_db?currentSchema=public&reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver
# 3. JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 4.
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
jwt.signerKey=r#nDf7F9siLbM3Z@M^Vq7/q^JSlTBPXn5Fnrx4n5Z/Dxv@trHbC#hv2CXPWisQ3h13@QeQpuvcXy8Zh9cgqTQw==
jwt.valid-duration=86400
jwt.refreshable-duration=604800000
#5. Aviation
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
#2c552495b69ba8e8e436798233a837ce
#5bef9e89f041797fa0c4d20b4a559807
aviationstack.api.key=${AVIATIONSTACK_KEY:2c552495b69ba8e8e436798233a837ce}
aviationstack.api.url=https://api.aviationstack.com/v1
logging.level.com.utc.flight_booking_service.inventory.client.AviationstackClient=DEBUG
#spring.cache.type=none
# 6.mail_service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nghianickmoi4@gmail.com
spring.mail.password=mqza apza wxio wrcq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#7. Vnpay
vnpay.tmn-code=YREXO76S
vnpay.hash-secret=R9KAZLINBCJAW6VK2884HSB9MNOMO8IK
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://direful-lifeful-esta.ngrok-free.dev/api/payments/vnpay-return
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
springdoc.swagger-ui.path=/swagger-ui.html