# 1. Server Configuration
server.port=8080
server.servlet.context-path=/api
spring.application.name=flight-booking-service

# 2. Database Connection
# Dung bien moi truong de bao mat thong tin Aiven
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. JWT Security
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
jwt.signerKey=${JWT_SECRET:r#nDf7F9siLbM3Z@M^Vq7/q^JSlTBPXn5Fnrx4n5Z/Dxv@trHbC#hv2CXPWisQ3h13@QeQpuvcXy8Zh9cgqTQw==}
jwt.valid-duration=86400
jwt.refreshable-duration=604800000

# 5. Aviation API
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
aviationstack.api.key=${AVIATIONSTACK_KEY:5bef9e89f041797fa0c4d20b4a559807}
aviationstack.api.url=https://api.aviationstack.com/v1
logging.level.com.utc.flight_booking_service.inventory.client.AviationstackClient=DEBUG

# 6. Mail Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nghianickmoi4@gmail.com
spring.mail.password=${MAIL_PASS:mqza apza wxio wrcq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 7. VNPay
vnpay.tmn-code=YREXO76S
vnpay.hash-secret=${VNPAY_SECRET:R9KAZLINBCJAW6VK2884HSB9MNOMO8IK}
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${VNPAY_RETURN_URL:https://direful-lifeful-esta.ngrok-free.dev/api/payments/vnpay-return}
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# 8. Others
springdoc.swagger-ui.path=/swagger-ui.html
spring.task.scheduling.pool.size=10
spring.task.scheduling.thread-name-prefix=my-job-

# 8. Redis
spring.data.redis.url=${REDIS_URL}