-- =========================================================================
-- ĐỔ DỮ LIỆU SÂN BAY (MASTER DATA) - PHIÊN BẢN GOD TIER (800+ SÂN BAY)
-- =========================================================================
INSERT INTO airports (code, name, city_code, country_code, timezone, created_at, updated_at) VALUES

-- ========================================
-- 1. VIỆT NAM (22 Sân bay thương mại)
-- ========================================
('HAN', 'Noi Bai International', 'HAN', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('SGN', 'Tan Son Nhat International', 'SGN', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('DAD', 'Da Nang International', 'DAD', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('PQC', 'Phu Quoc International', 'PQC', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('CXR', 'Cam Ranh International', 'CXR', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('HPH', 'Cat Bi International', 'HPH', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('VCA', 'Can Tho International', 'VCA', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('VII', 'Vinh International', 'VII', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('HUI', 'Phu Bai International', 'HUI', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('UIH', 'Phu Cat Airport', 'UIH', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('VDO', 'Van Don International', 'VDO', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('DLI', 'Lien Khuong Airport', 'DLI', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('BMV', 'Buon Ma Thuot Airport', 'BMV', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('PXU', 'Pleiku Airport', 'PXU', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('TBB', 'Tuy Hoa Airport', 'TBB', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('VDZ', 'Con Dao Airport', 'VDZ', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('THD', 'Tho Xuan Airport', 'THD', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('VKG', 'Rach Gia Airport', 'VKG', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('VCS', 'Con Dao Airport', 'VCS', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('DIN', 'Dien Bien Phu Airport', 'DIN', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('VCL', 'Chu Lai International', 'VCL', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),
('CAH', 'Ca Mau Airport', 'CAH', 'VN', 'Asia/Ho_Chi_Minh', NOW(), NOW()),

-- ========================================
-- 2. BẮC MỸ (Hoa Kỳ & Canada - Mở rộng tối đa)
-- ========================================
-- US Hubs & Major
('ATL', 'Hartsfield-Jackson Atlanta', 'ATL', 'US', 'America/New_York', NOW(), NOW()),
('DFW', 'Dallas/Fort Worth', 'DFW', 'US', 'America/Chicago', NOW(), NOW()),
('DEN', 'Denver International', 'DEN', 'US', 'America/Denver', NOW(), NOW()),
('ORD', 'O''Hare International', 'CHI', 'US', 'America/Chicago', NOW(), NOW()),
('LAX', 'Los Angeles International', 'LAX', 'US', 'America/Los_Angeles', NOW(), NOW()),
('JFK', 'John F. Kennedy', 'NYC', 'US', 'America/New_York', NOW(), NOW()),
('LAS', 'Harry Reid International', 'LAS', 'US', 'America/Los_Angeles', NOW(), NOW()),
('MCO', 'Orlando International', 'ORL', 'US', 'America/New_York', NOW(), NOW()),
('MIA', 'Miami International', 'MIA', 'US', 'America/New_York', NOW(), NOW()),
('CLT', 'Charlotte Douglas', 'CLT', 'US', 'America/New_York', NOW(), NOW()),
('SEA', 'Seattle-Tacoma', 'SEA', 'US', 'America/Los_Angeles', NOW(), NOW()),
('PHX', 'Phoenix Sky Harbor', 'PHX', 'US', 'America/Phoenix', NOW(), NOW()),
('EWR', 'Newark Liberty', 'NYC', 'US', 'America/New_York', NOW(), NOW()),
('SFO', 'San Francisco International', 'SFO', 'US', 'America/Los_Angeles', NOW(), NOW()),
('IAH', 'George Bush Intercontinental', 'HOU', 'US', 'America/Chicago', NOW(), NOW()),
('BOS', 'Logan International', 'BOS', 'US', 'America/New_York', NOW(), NOW()),
('SLC', 'Salt Lake City', 'SLC', 'US', 'America/Denver', NOW(), NOW()),
('DTW', 'Detroit Metropolitan', 'DTT', 'US', 'America/Detroit', NOW(), NOW()),
('MSP', 'Minneapolis-Saint Paul', 'MSP', 'US', 'America/Chicago', NOW(), NOW()),
('PHL', 'Philadelphia International', 'PHL', 'US', 'America/New_York', NOW(), NOW()),
('LGA', 'LaGuardia Airport', 'NYC', 'US', 'America/New_York', NOW(), NOW()),
('BWI', 'Baltimore/Washington', 'BWI', 'US', 'America/New_York', NOW(), NOW()),
('IAD', 'Washington Dulles', 'WAS', 'US', 'America/New_York', NOW(), NOW()),
('DCA', 'Ronald Reagan Washington', 'WAS', 'US', 'America/New_York', NOW(), NOW()),
('SAN', 'San Diego International', 'SAN', 'US', 'America/Los_Angeles', NOW(), NOW()),
('MDW', 'Chicago Midway', 'CHI', 'US', 'America/Chicago', NOW(), NOW()),
('TPA', 'Tampa International', 'TPA', 'US', 'America/New_York', NOW(), NOW()),
('HNL', 'Daniel K. Inouye', 'HNL', 'US', 'Pacific/Honolulu', NOW(), NOW()),
-- US Secondary Hubs (Mới thêm)
('PDX', 'Portland International', 'PDX', 'US', 'America/Los_Angeles', NOW(), NOW()),
('BNA', 'Nashville International', 'BNA', 'US', 'America/Chicago', NOW(), NOW()),
('AUS', 'Austin-Bergstrom', 'AUS', 'US', 'America/Chicago', NOW(), NOW()),
('DAL', 'Dallas Love Field', 'DFW', 'US', 'America/Chicago', NOW(), NOW()),
('SJC', 'Norman Y. Mineta San Jose', 'SJC', 'US', 'America/Los_Angeles', NOW(), NOW()),
('HOU', 'William P. Hobby', 'HOU', 'US', 'America/Chicago', NOW(), NOW()),
('RDU', 'Raleigh-Durham', 'RDU', 'US', 'America/New_York', NOW(), NOW()),
('MSY', 'Louis Armstrong New Orleans', 'MSY', 'US', 'America/Chicago', NOW(), NOW()),
('OAK', 'Oakland International', 'OAK', 'US', 'America/Los_Angeles', NOW(), NOW()),
('SMF', 'Sacramento International', 'SMF', 'US', 'America/Los_Angeles', NOW(), NOW()),
('MCI', 'Kansas City International', 'MCI', 'US', 'America/Chicago', NOW(), NOW()),
('CLE', 'Cleveland Hopkins', 'CLE', 'US', 'America/New_York', NOW(), NOW()),
('IND', 'Indianapolis International', 'IND', 'US', 'America/New_York', NOW(), NOW()),
('SAT', 'San Antonio International', 'SAT', 'US', 'America/Chicago', NOW(), NOW()),
('CVG', 'Cincinnati/Northern Kentucky', 'CVG', 'US', 'America/New_York', NOW(), NOW()),
('PIT', 'Pittsburgh International', 'PIT', 'US', 'America/New_York', NOW(), NOW()),
('SJU', 'Luis Muñoz Marín', 'SJU', 'PR', 'America/Puerto_Rico', NOW(), NOW()),
('ANC', 'Ted Stevens Anchorage', 'ANC', 'US', 'America/Anchorage', NOW(), NOW()),
('MEM', 'Memphis International', 'MEM', 'US', 'America/Chicago', NOW(), NOW()),
('RSW', 'Southwest Florida', 'RSW', 'US', 'America/New_York', NOW(), NOW()),
('SNA', 'John Wayne Airport', 'SNA', 'US', 'America/Los_Angeles', NOW(), NOW()),
('MKE', 'Milwaukee Mitchell', 'MKE', 'US', 'America/Chicago', NOW(), NOW()),
('OMA', 'Eppley Airfield', 'OMA', 'US', 'America/Chicago', NOW(), NOW()),
('BOI', 'Boise Airport', 'BOI', 'US', 'America/Boise', NOW(), NOW()),
('RNO', 'Reno-Tahoe International', 'RNO', 'US', 'America/Los_Angeles', NOW(), NOW()),
('ABQ', 'Albuquerque International', 'ABQ', 'US', 'America/Denver', NOW(), NOW()),
('TUS', 'Tucson International', 'TUS', 'US', 'America/Phoenix', NOW(), NOW()),
('OKC', 'Will Rogers World', 'OKC', 'US', 'America/Chicago', NOW(), NOW()),
('ORF', 'Norfolk International', 'ORF', 'US', 'America/New_York', NOW(), NOW()),
('JAX', 'Jacksonville International', 'JAX', 'US', 'America/New_York', NOW(), NOW()),
-- Canada
('YYZ', 'Toronto Pearson', 'YTO', 'CA', 'America/Toronto', NOW(), NOW()),
('YVR', 'Vancouver International', 'YVR', 'CA', 'America/Vancouver', NOW(), NOW()),
('YUL', 'Montréal-Pierre Elliott Trudeau', 'YMQ', 'CA', 'America/Toronto', NOW(), NOW()),
('YYC', 'Calgary International', 'YYC', 'CA', 'America/Edmonton', NOW(), NOW()),
('YEG', 'Edmonton International', 'YEA', 'CA', 'America/Edmonton', NOW(), NOW()),
('YOW', 'Ottawa Macdonald-Cartier', 'YOW', 'CA', 'America/Toronto', NOW(), NOW()),
('YHZ', 'Halifax Stanfield', 'YHZ', 'CA', 'America/Halifax', NOW(), NOW()),
('YWG', 'Winnipeg James Armstrong', 'YWG', 'CA', 'America/Winnipeg', NOW(), NOW()),
('YTZ', 'Billy Bishop Toronto City', 'YTO', 'CA', 'America/Toronto', NOW(), NOW()),
('YQB', 'Québec City Jean Lesage', 'YQB', 'CA', 'America/Toronto', NOW(), NOW()),

-- ========================================
-- 3. CHÂU ÂU (Mở rộng toàn diện)
-- ========================================
-- UK & Ireland
('LHR', 'Heathrow Airport', 'LON', 'GB', 'Europe/London', NOW(), NOW()),
('LGW', 'Gatwick Airport', 'LON', 'GB', 'Europe/London', NOW(), NOW()),
('STN', 'London Stansted', 'LON', 'GB', 'Europe/London', NOW(), NOW()),
('LTN', 'Luton Airport', 'LON', 'GB', 'Europe/London', NOW(), NOW()),
('MAN', 'Manchester Airport', 'MAN', 'GB', 'Europe/London', NOW(), NOW()),
('EDI', 'Edinburgh Airport', 'EDI', 'GB', 'Europe/London', NOW(), NOW()),
('BHX', 'Birmingham Airport', 'BHX', 'GB', 'Europe/London', NOW(), NOW()),
('GLA', 'Glasgow Airport', 'GLA', 'GB', 'Europe/London', NOW(), NOW()),
('BRS', 'Bristol Airport', 'BRS', 'GB', 'Europe/London', NOW(), NOW()),
('NCL', 'Newcastle International', 'NCL', 'GB', 'Europe/London', NOW(), NOW()),
('LBA', 'Leeds Bradford', 'LBA', 'GB', 'Europe/London', NOW(), NOW()),
('EMA', 'East Midlands', 'EMA', 'GB', 'Europe/London', NOW(), NOW()),
('BFS', 'Belfast International', 'BFS', 'GB', 'Europe/London', NOW(), NOW()),
('BHD', 'George Best Belfast City', 'BHD', 'GB', 'Europe/London', NOW(), NOW()),
('DUB', 'Dublin Airport', 'DUB', 'IE', 'Europe/Dublin', NOW(), NOW()),
('ORK', 'Cork Airport', 'ORK', 'IE', 'Europe/Dublin', NOW(), NOW()),
('SNN', 'Shannon Airport', 'SNN', 'IE', 'Europe/Dublin', NOW(), NOW()),
-- France
('CDG', 'Charles de Gaulle', 'PAR', 'FR', 'Europe/Paris', NOW(), NOW()),
('ORY', 'Orly Airport', 'PAR', 'FR', 'Europe/Paris', NOW(), NOW()),
('NCE', 'Nice Côte d''Azur', 'NCE', 'FR', 'Europe/Paris', NOW(), NOW()),
('LYS', 'Lyon-Saint Exupéry', 'LYS', 'FR', 'Europe/Paris', NOW(), NOW()),
('MRS', 'Marseille Provence', 'MRS', 'FR', 'Europe/Paris', NOW(), NOW()),
('TLS', 'Toulouse-Blagnac', 'TLS', 'FR', 'Europe/Paris', NOW(), NOW()),
('BOD', 'Bordeaux-Mérignac', 'BOD', 'FR', 'Europe/Paris', NOW(), NOW()),
('NTE', 'Nantes Atlantique', 'NTE', 'FR', 'Europe/Paris', NOW(), NOW()),
('BVA', 'Paris Beauvais', 'PAR', 'FR', 'Europe/Paris', NOW(), NOW()),
('LIL', 'Lille Airport', 'LIL', 'FR', 'Europe/Paris', NOW(), NOW()),
-- Germany
('FRA', 'Frankfurt Airport', 'FRA', 'DE', 'Europe/Berlin', NOW(), NOW()),
('MUC', 'Munich Airport', 'MUC', 'DE', 'Europe/Berlin', NOW(), NOW()),
('BER', 'Berlin Brandenburg', 'BER', 'DE', 'Europe/Berlin', NOW(), NOW()),
('DUS', 'Düsseldorf Airport', 'DUS', 'DE', 'Europe/Berlin', NOW(), NOW()),
('HAM', 'Hamburg Airport', 'HAM', 'DE', 'Europe/Berlin', NOW(), NOW()),
('STR', 'Stuttgart Airport', 'STR', 'DE', 'Europe/Berlin', NOW(), NOW()),
('CGN', 'Cologne Bonn', 'CGN', 'DE', 'Europe/Berlin', NOW(), NOW()),
('HAJ', 'Hannover Airport', 'HAJ', 'DE', 'Europe/Berlin', NOW(), NOW()),
('NUE', 'Nuremberg Airport', 'NUE', 'DE', 'Europe/Berlin', NOW(), NOW()),
('LEJ', 'Leipzig/Halle', 'LEJ', 'DE', 'Europe/Berlin', NOW(), NOW()),
('BRE', 'Bremen Airport', 'BRE', 'DE', 'Europe/Berlin', NOW(), NOW()),
-- Italy
('FCO', 'Leonardo da Vinci-Fiumicino', 'ROM', 'IT', 'Europe/Rome', NOW(), NOW()),
('CIA', 'Ciampino', 'ROM', 'IT', 'Europe/Rome', NOW(), NOW()),
('MXP', 'Milan Malpensa', 'MIL', 'IT', 'Europe/Rome', NOW(), NOW()),
('LIN', 'Linate Airport', 'MIL', 'IT', 'Europe/Rome', NOW(), NOW()),
('BGY', 'Orio al Serio (Bergamo)', 'MIL', 'IT', 'Europe/Rome', NOW(), NOW()),
('VCE', 'Venice Marco Polo', 'VCE', 'IT', 'Europe/Rome', NOW(), NOW()),
('NAP', 'Naples International', 'NAP', 'IT', 'Europe/Rome', NOW(), NOW()),
('BLQ', 'Bologna Guglielmo Marconi', 'BLQ', 'IT', 'Europe/Rome', NOW(), NOW()),
('PMO', 'Falcone Borsellino', 'PMO', 'IT', 'Europe/Rome', NOW(), NOW()),
('CTA', 'Catania-Fontanarossa', 'CTA', 'IT', 'Europe/Rome', NOW(), NOW()),
('PSA', 'Pisa International', 'PSA', 'IT', 'Europe/Rome', NOW(), NOW()),
('FLR', 'Florence Airport', 'FLR', 'IT', 'Europe/Rome', NOW(), NOW()),
('CAG', 'Cagliari Elmas', 'CAG', 'IT', 'Europe/Rome', NOW(), NOW()),
('OLB', 'Olbia Costa Smeralda', 'OLB', 'IT', 'Europe/Rome', NOW(), NOW()),
('TRN', 'Turin Airport', 'TRN', 'IT', 'Europe/Rome', NOW(), NOW()),
('GOA', 'Genoa Cristoforo Colombo', 'GOA', 'IT', 'Europe/Rome', NOW(), NOW()),
('VRN', 'Verona Villafranca', 'VRN', 'IT', 'Europe/Rome', NOW(), NOW()),
-- Spain & Portugal
('MAD', 'Adolfo Suárez Madrid-Barajas', 'MAD', 'ES', 'Europe/Madrid', NOW(), NOW()),
('BCN', 'Barcelona-El Prat', 'BCN', 'ES', 'Europe/Madrid', NOW(), NOW()),
('PMI', 'Palma de Mallorca', 'PMI', 'ES', 'Europe/Madrid', NOW(), NOW()),
('AGP', 'Málaga Airport', 'AGP', 'ES', 'Europe/Madrid', NOW(), NOW()),
('ALC', 'Alicante-Elche', 'ALC', 'ES', 'Europe/Madrid', NOW(), NOW()),
('VLC', 'Valencia Airport', 'VLC', 'ES', 'Europe/Madrid', NOW(), NOW()),
('TFS', 'Tenerife South', 'TCI', 'ES', 'Atlantic/Canary', NOW(), NOW()),
('TFN', 'Tenerife North', 'TCI', 'ES', 'Atlantic/Canary', NOW(), NOW()),
('LPA', 'Gran Canaria', 'LPA', 'ES', 'Atlantic/Canary', NOW(), NOW()),
('IBZ', 'Ibiza Airport', 'IBZ', 'ES', 'Europe/Madrid', NOW(), NOW()),
('SVQ', 'Seville Airport', 'SVQ', 'ES', 'Europe/Madrid', NOW(), NOW()),
('BIO', 'Bilbao Airport', 'BIO', 'ES', 'Europe/Madrid', NOW(), NOW()),
('SCQ', 'Santiago de Compostela', 'SCQ', 'ES', 'Europe/Madrid', NOW(), NOW()),
('LIS', 'Lisbon Airport', 'LIS', 'PT', 'Europe/Lisbon', NOW(), NOW()),
('OPO', 'Francisco Sá Carneiro', 'OPO', 'PT', 'Europe/Lisbon', NOW(), NOW()),
('FAO', 'Faro Airport', 'FAO', 'PT', 'Europe/Lisbon', NOW(), NOW()),
('FNC', 'Madeira Airport', 'FNC', 'PT', 'Atlantic/Madeira', NOW(), NOW()),
('PDL', 'João Paulo II (Azores)', 'PDL', 'PT', 'Atlantic/Azores', NOW(), NOW()),
-- Netherlands, Belgium, Switzerland, Austria
('AMS', 'Amsterdam Schiphol', 'AMS', 'NL', 'Europe/Amsterdam', NOW(), NOW()),
('EIN', 'Eindhoven Airport', 'EIN', 'NL', 'Europe/Amsterdam', NOW(), NOW()),
('RTM', 'Rotterdam The Hague', 'RTM', 'NL', 'Europe/Amsterdam', NOW(), NOW()),
('BRU', 'Brussels Airport', 'BRU', 'BE', 'Europe/Brussels', NOW(), NOW()),
('CRL', 'Brussels South Charleroi', 'BRU', 'BE', 'Europe/Brussels', NOW(), NOW()),
('ZRH', 'Zurich Airport', 'ZRH', 'CH', 'Europe/Zurich', NOW(), NOW()),
('GVA', 'Geneva Airport', 'GVA', 'CH', 'Europe/Zurich', NOW(), NOW()),
('BSL', 'EuroAirport Basel Mulhouse', 'EAP', 'CH', 'Europe/Zurich', NOW(), NOW()),
('VIE', 'Vienna International', 'VIE', 'AT', 'Europe/Vienna', NOW(), NOW()),
('SZG', 'Salzburg Airport', 'SZG', 'AT', 'Europe/Vienna', NOW(), NOW()),
('INN', 'Innsbruck Airport', 'INN', 'AT', 'Europe/Vienna', NOW(), NOW()),
-- Nordics (Scandinavia & Baltics)
('CPH', 'Copenhagen Airport', 'CPH', 'DK', 'Europe/Copenhagen', NOW(), NOW()),
('BLL', 'Billund Airport', 'BLL', 'DK', 'Europe/Copenhagen', NOW(), NOW()),
('OSL', 'Oslo Airport, Gardermoen', 'OSL', 'NO', 'Europe/Oslo', NOW(), NOW()),
('BGO', 'Bergen Airport', 'BGO', 'NO', 'Europe/Oslo', NOW(), NOW()),
('TRD', 'Trondheim Airport', 'TRD', 'NO', 'Europe/Oslo', NOW(), NOW()),
('SVG', 'Stavanger Airport', 'SVG', 'NO', 'Europe/Oslo', NOW(), NOW()),
('ARN', 'Stockholm Arlanda', 'STO', 'SE', 'Europe/Stockholm', NOW(), NOW()),
('GOT', 'Göteborg Landvetter', 'GOT', 'SE', 'Europe/Stockholm', NOW(), NOW()),
('BMA', 'Stockholm Bromma', 'STO', 'SE', 'Europe/Stockholm', NOW(), NOW()),
('MMX', 'Malmö Airport', 'MMX', 'SE', 'Europe/Stockholm', NOW(), NOW()),
('HEL', 'Helsinki Airport', 'HEL', 'FI', 'Europe/Helsinki', NOW(), NOW()),
('KEF', 'Keflavík International', 'REK', 'IS', 'Atlantic/Reykjavik', NOW(), NOW()),
('RIX', 'Riga International', 'RIX', 'LV', 'Europe/Riga', NOW(), NOW()),
('VNO', 'Vilnius Airport', 'VNO', 'LT', 'Europe/Vilnius', NOW(), NOW()),
('TLL', 'Tallinn Airport', 'TLL', 'EE', 'Europe/Tallinn', NOW(), NOW()),
-- Eastern Europe & Balkans
('WAW', 'Warsaw Chopin', 'WAW', 'PL', 'Europe/Warsaw', NOW(), NOW()),
('KRK', 'John Paul II Kraków', 'KRK', 'PL', 'Europe/Warsaw', NOW(), NOW()),
('GDN', 'Gdańsk Lech Wałęsa', 'GDN', 'PL', 'Europe/Warsaw', NOW(), NOW()),
('KTW', 'Katowice Airport', 'KTW', 'PL', 'Europe/Warsaw', NOW(), NOW()),
('WRO', 'Copernicus Wrocław', 'WRO', 'PL', 'Europe/Warsaw', NOW(), NOW()),
('PRG', 'Václav Havel Prague', 'PRG', 'CZ', 'Europe/Prague', NOW(), NOW()),
('BUD', 'Budapest Ferenc Liszt', 'BUD', 'HU', 'Europe/Budapest', NOW(), NOW()),
('OTP', 'Henri Coandă Bucharest', 'BUH', 'RO', 'Europe/Bucharest', NOW(), NOW()),
('CLJ', 'Cluj International', 'CLJ', 'RO', 'Europe/Bucharest', NOW(), NOW()),
('SOF', 'Sofia Airport', 'SOF', 'BG', 'Europe/Sofia', NOW(), NOW()),
('BEG', 'Belgrade Nikola Tesla', 'BEG', 'RS', 'Europe/Belgrade', NOW(), NOW()),
('ZAG', 'Zagreb Airport', 'ZAG', 'HR', 'Europe/Zagreb', NOW(), NOW()),
('SPU', 'Split Airport', 'SPU', 'HR', 'Europe/Zagreb', NOW(), NOW()),
('DBV', 'Dubrovnik Airport', 'DBV', 'HR', 'Europe/Zagreb', NOW(), NOW()),
('LJU', 'Ljubljana Jože Pučnik', 'LJU', 'SI', 'Europe/Ljubljana', NOW(), NOW()),
('ATH', 'Athens International', 'ATH', 'GR', 'Europe/Athens', NOW(), NOW()),
('SKG', 'Thessaloniki Airport', 'SKG', 'GR', 'Europe/Athens', NOW(), NOW()),
('HER', 'Heraklion International', 'HER', 'GR', 'Europe/Athens', NOW(), NOW()),
('RHO', 'Rhodes International', 'RHO', 'GR', 'Europe/Athens', NOW(), NOW()),
('CFU', 'Corfu International', 'CFU', 'GR', 'Europe/Athens', NOW(), NOW()),
('JTR', 'Santorini Airport', 'JTR', 'GR', 'Europe/Athens', NOW(), NOW()),
('JMK', 'Mykonos Airport', 'JMK', 'GR', 'Europe/Athens', NOW(), NOW()),
('LCA', 'Larnaca International', 'LCA', 'CY', 'Asia/Nicosia', NOW(), NOW()),
('PFO', 'Paphos International', 'PFO', 'CY', 'Asia/Nicosia', NOW(), NOW()),
-- Turkey & Russia/CIS
('IST', 'Istanbul Airport', 'IST', 'TR', 'Europe/Istanbul', NOW(), NOW()),
('SAW', 'Sabiha Gökçen', 'IST', 'TR', 'Europe/Istanbul', NOW(), NOW()),
('AYT', 'Antalya Airport', 'AYT', 'TR', 'Europe/Istanbul', NOW(), NOW()),
('ESB', 'Ankara Esenboğa', 'ANK', 'TR', 'Europe/Istanbul', NOW(), NOW()),
('ADB', 'İzmir Adnan Menderes', 'IZM', 'TR', 'Europe/Istanbul', NOW(), NOW()),
('DLM', 'Dalaman Airport', 'DLM', 'TR', 'Europe/Istanbul', NOW(), NOW()),
('BJV', 'Milas-Bodrum', 'BJV', 'TR', 'Europe/Istanbul', NOW(), NOW()),
('SVO', 'Sheremetyevo', 'MOW', 'RU', 'Europe/Moscow', NOW(), NOW()),
('DME', 'Domodedovo', 'MOW', 'RU', 'Europe/Moscow', NOW(), NOW()),
('VKO', 'Vnukovo', 'MOW', 'RU', 'Europe/Moscow', NOW(), NOW()),
('LED', 'Pulkovo', 'LED', 'RU', 'Europe/Moscow', NOW(), NOW()),
('AER', 'Sochi International', 'AER', 'RU', 'Europe/Moscow', NOW(), NOW()),
('SVX', 'Koltsovo', 'SVX', 'RU', 'Asia/Yekaterinburg', NOW(), NOW()),
('OVB', 'Tolmachevo', 'OVB', 'RU', 'Asia/Novosibirsk', NOW(), NOW()),
('GYD', 'Heydar Aliyev (Baku)', 'BAK', 'AZ', 'Asia/Baku', NOW(), NOW()),
('TBS', 'Tbilisi International', 'TBS', 'GE', 'Asia/Tbilisi', NOW(), NOW()),
('EVN', 'Zvartnots International', 'EVN', 'AM', 'Asia/Yerevan', NOW(), NOW()),
('ALA', 'Almaty International', 'ALA', 'KZ', 'Asia/Almaty', NOW(), NOW()),
('NQZ', 'Nursultan Nazarbayev', 'NQZ', 'KZ', 'Asia/Almaty', NOW(), NOW()),
('TAS', 'Islam Karimov Tashkent', 'TAS', 'UZ', 'Asia/Tashkent', NOW(), NOW()),

-- ========================================
-- 4. TRUNG QUỐC, NHẬT BẢN, HÀN QUỐC
-- ========================================
-- Trung Quốc (China - Rất nhiều)
('PEK', 'Beijing Capital', 'BJS', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('PKX', 'Beijing Daxing', 'BJS', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('PVG', 'Shanghai Pudong', 'SHA', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('SHA', 'Shanghai Hongqiao', 'SHA', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('CAN', 'Guangzhou Baiyun', 'CAN', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('SZX', 'Shenzhen Bao''an', 'SZX', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('CTU', 'Chengdu Shuangliu', 'CTU', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('TFU', 'Chengdu Tianfu', 'CTU', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('CKG', 'Chongqing Jiangbei', 'CKG', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('XIY', 'Xi''an Xianyang', 'SIA', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('HGH', 'Hangzhou Xiaoshan', 'HGH', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('KMG', 'Kunming Changshui', 'KMG', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('XMN', 'Xiamen Gaoqi', 'XMN', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('WUH', 'Wuhan Tianhe', 'WUH', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('CSX', 'Changsha Huanghua', 'CSX', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('NKG', 'Nanjing Lukou', 'NKG', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('CGO', 'Zhengzhou Xinzheng', 'CGO', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('URC', 'Ürümqi Diwopu', 'URC', 'CN', 'Asia/Urumqi', NOW(), NOW()),
('HRB', 'Harbin Taiping', 'HRB', 'CN', 'Asia/Harbin', NOW(), NOW()),
('DLC', 'Dalian Zhoushuizi', 'DLC', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('TSN', 'Tianjin Binhai', 'TSN', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('TAO', 'Qingdao Jiaodong', 'TAO', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('SYX', 'Sanya Phoenix', 'SYX', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('HAK', 'Haikou Meilan', 'HAK', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('CGQ', 'Changchun Longjia', 'CGQ', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('SHE', 'Shenyang Taoxian', 'SHE', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('NGB', 'Ningbo Lishe', 'NGB', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('WNZ', 'Wenzhou Longwan', 'WNZ', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('FOC', 'Fuzhou Changle', 'FOC', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('TYN', 'Taiyuan Wusu', 'TYN', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('KWE', 'Guiyang Longdongbao', 'KWE', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('HET', 'Hohhot Baita', 'HET', 'CN', 'Asia/Shanghai', NOW(), NOW()),
('LHW', 'Lanzhou Zhongchuan', 'LHW', 'CN', 'Asia/Shanghai', NOW(), NOW()),
-- Hồng Kông, Ma Cao, Đài Loan
('HKG', 'Hong Kong International', 'HKG', 'HK', 'Asia/Hong_Kong', NOW(), NOW()),
('MFM', 'Macau International', 'MFM', 'MO', 'Asia/Macau', NOW(), NOW()),
('TPE', 'Taoyuan International', 'TPE', 'TW', 'Asia/Taipei', NOW(), NOW()),
('TSA', 'Taipei Songshan', 'TPE', 'TW', 'Asia/Taipei', NOW(), NOW()),
('KHH', 'Kaohsiung International', 'KHH', 'TW', 'Asia/Taipei', NOW(), NOW()),
('TXG', 'Taichung International', 'TXG', 'TW', 'Asia/Taipei', NOW(), NOW()),
-- Nhật Bản
('NRT', 'Narita International', 'TYO', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('HND', 'Tokyo Haneda', 'TYO', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('KIX', 'Kansai International', 'OSA', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('ITM', 'Osaka International', 'OSA', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('CTS', 'New Chitose (Sapporo)', 'SPK', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('FUK', 'Fukuoka Airport', 'FUK', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('NGO', 'Chubu Centrair', 'NGO', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('OKA', 'Naha Airport', 'OKA', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('KOJ', 'Kagoshima Airport', 'KOJ', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('HIJ', 'Hiroshima Airport', 'HIJ', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('SDJ', 'Sendai Airport', 'SDJ', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('KIJ', 'Niigata Airport', 'KIJ', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('FSZ', 'Mt. Fuji Shizuoka', 'FSZ', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('UKB', 'Kobe Airport', 'UKB', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('TAK', 'Takamatsu Airport', 'TAK', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('MYJ', 'Matsuyama Airport', 'MYJ', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('NGS', 'Nagasaki Airport', 'NGS', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('KMJ', 'Kumamoto Airport', 'KMJ', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('ISG', 'New Ishigaki Airport', 'ISG', 'JP', 'Asia/Tokyo', NOW(), NOW()),
('HKD', 'Hakodate Airport', 'HKD', 'JP', 'Asia/Tokyo', NOW(), NOW()),
-- Hàn Quốc
('ICN', 'Incheon International', 'SEL', 'KR', 'Asia/Seoul', NOW(), NOW()),
('GMP', 'Gimpo International', 'SEL', 'KR', 'Asia/Seoul', NOW(), NOW()),
('CJU', 'Jeju International', 'CJU', 'KR', 'Asia/Seoul', NOW(), NOW()),
('PUS', 'Gimhae International', 'PUS', 'KR', 'Asia/Seoul', NOW(), NOW()),
('CJJ', 'Cheongju International', 'CJJ', 'KR', 'Asia/Seoul', NOW(), NOW()),
('TAE', 'Daegu International', 'TAE', 'KR', 'Asia/Seoul', NOW(), NOW()),
('MWX', 'Muan International', 'MWX', 'KR', 'Asia/Seoul', NOW(), NOW()),

-- ========================================
-- 5. CHÂU Á (Phần còn lại) & TRUNG ĐÔNG
-- ========================================
-- Ấn Độ
('DEL', 'Indira Gandhi (Delhi)', 'DEL', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('BOM', 'Chhatrapati Shivaji (Mumbai)', 'BOM', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('BLR', 'Kempegowda (Bangalore)', 'BLR', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('MAA', 'Chennai International', 'MAA', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('CCU', 'Netaji Subhas Chandra Bose (Kolkata)', 'CCU', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('HYD', 'Rajiv Gandhi (Hyderabad)', 'HYD', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('COK', 'Cochin International', 'COK', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('AMD', 'Sardar Vallabhbhai Patel (Ahmedabad)', 'AMD', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('PNQ', 'Pune Airport', 'PNQ', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('GOI', 'Dabolim Airport (Goa)', 'GOI', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('GOX', 'Manohar International (Goa)', 'GOI', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('TRV', 'Trivandrum International', 'TRV', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('CCJ', 'Calicut International', 'CCJ', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('IXE', 'Mangalore International', 'IXE', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('STV', 'Surat International', 'STV', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('ATQ', 'Sri Guru Ram Dass Jee (Amritsar)', 'ATQ', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('LKO', 'Chaudhary Charan Singh (Lucknow)', 'LKO', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('VNS', 'Lal Bahadur Shastri (Varanasi)', 'VNS', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('PAT', 'Jay Prakash Narayan (Patna)', 'PAT', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('GAU', 'Lokpriya Gopinath Bordoloi (Guwahati)', 'GAU', 'IN', 'Asia/Kolkata', NOW(), NOW()),
('BBI', 'Biju Patnaik (Bhubaneswar)', 'BBI', 'IN', 'Asia/Kolkata', NOW(), NOW()),
-- Đông Nam Á (Thái Lan, Indo, Phi, Myan...)
('RGN', 'Yangon International', 'RGN', 'MM', 'Asia/Yangon', NOW(), NOW()),
('MDL', 'Mandalay International', 'MDL', 'MM', 'Asia/Yangon', NOW(), NOW()),
('PNH', 'Phnom Penh International', 'PNH', 'KH', 'Asia/Phnom_Penh', NOW(), NOW()),
('REP', 'Siem Reap International', 'REP', 'KH', 'Asia/Phnom_Penh', NOW(), NOW()),
('VTE', 'Wattay International', 'VTE', 'LA', 'Asia/Vientiane', NOW(), NOW()),
('LPQ', 'Luang Prabang International', 'LPQ', 'LA', 'Asia/Vientiane', NOW(), NOW()),
('CEI', 'Mae Fah Luang - Chiang Rai', 'CEI', 'TH', 'Asia/Bangkok', NOW(), NOW()),
('HDY', 'Hat Yai International', 'HDY', 'TH', 'Asia/Bangkok', NOW(), NOW()),
('URT', 'Surat Thani Airport', 'URT', 'TH', 'Asia/Bangkok', NOW(), NOW()),
('BDO', 'Husein Sastranegara (Bandung)', 'BDO', 'ID', 'Asia/Jakarta', NOW(), NOW()),
('JOG', 'Adisutjipto International', 'JOG', 'ID', 'Asia/Jakarta', NOW(), NOW()),
('SRG', 'Ahmad Yani International (Semarang)', 'SRG', 'ID', 'Asia/Jakarta', NOW(), NOW()),
('PNK', 'Supadio International (Pontianak)', 'PNK', 'ID', 'Asia/Jakarta', NOW(), NOW()),
('BPN', 'Sultan Aji Muhammad Sulaiman (Balikpapan)', 'BPN', 'ID', 'Asia/Makassar', NOW(), NOW()),
('DVO', 'Francisco Bangoy (Davao)', 'DVO', 'PH', 'Asia/Manila', NOW(), NOW()),
('ILO', 'Iloilo International', 'ILO', 'PH', 'Asia/Manila', NOW(), NOW()),
('KLO', 'Kalibo International', 'KLO', 'PH', 'Asia/Manila', NOW(), NOW()),
('PPS', 'Puerto Princesa International', 'PPS', 'PH', 'Asia/Manila', NOW(), NOW()),
('DIL', 'Presidente Nicolau Lobato (Dili)', 'DIL', 'TL', 'Asia/Dili', NOW(), NOW()),
-- Nam Á khác
('KHI', 'Jinnah International', 'KHI', 'PK', 'Asia/Karachi', NOW(), NOW()),
('LHE', 'Allama Iqbal International', 'LHE', 'PK', 'Asia/Karachi', NOW(), NOW()),
('ISB', 'Islamabad International', 'ISB', 'PK', 'Asia/Karachi', NOW(), NOW()),
('PEW', 'Bacha Khan International (Peshawar)', 'PEW', 'PK', 'Asia/Karachi', NOW(), NOW()),
('DAC', 'Hazrat Shahjalal', 'DAC', 'BD', 'Asia/Dhaka', NOW(), NOW()),
('CGP', 'Shah Amanat (Chittagong)', 'CGP', 'BD', 'Asia/Dhaka', NOW(), NOW()),
('CMB', 'Bandaranaike International', 'CMB', 'LK', 'Asia/Colombo', NOW(), NOW()),
('KTM', 'Tribhuvan International', 'KTM', 'NP', 'Asia/Kathmandu', NOW(), NOW()),
('MLE', 'Velana International', 'MLE', 'MV', 'Indian/Maldives', NOW(), NOW()),
('KBL', 'Kabul International', 'KBL', 'AF', 'Asia/Kabul', NOW(), NOW()),
-- Trung Đông
('DXB', 'Dubai International', 'DXB', 'AE', 'Asia/Dubai', NOW(), NOW()),
('AUH', 'Zayed International', 'AUH', 'AE', 'Asia/Dubai', NOW(), NOW()),
('SHJ', 'Sharjah International', 'SHJ', 'AE', 'Asia/Dubai', NOW(), NOW()),
('DWC', 'Al Maktoum International', 'DWC', 'AE', 'Asia/Dubai', NOW(), NOW()),
('DOH', 'Hamad International', 'DOH', 'QA', 'Asia/Qatar', NOW(), NOW()),
('RUH', 'King Khalid International', 'RUH', 'SA', 'Asia/Riyadh', NOW(), NOW()),
('JED', 'King Abdulaziz International', 'JED', 'SA', 'Asia/Riyadh', NOW(), NOW()),
('DMM', 'King Fahd International', 'DMM', 'SA', 'Asia/Riyadh', NOW(), NOW()),
('MED', 'Prince Mohammad bin Abdulaziz', 'MED', 'SA', 'Asia/Riyadh', NOW(), NOW()),
('MCT', 'Muscat International', 'MCT', 'OM', 'Asia/Muscat', NOW(), NOW()),
('SLL', 'Salalah Airport', 'SLL', 'OM', 'Asia/Muscat', NOW(), NOW()),
('BAH', 'Bahrain International', 'BAH', 'BH', 'Asia/Bahrain', NOW(), NOW()),
('KWI', 'Kuwait International', 'KWI', 'KW', 'Asia/Kuwait', NOW(), NOW()),
('AMM', 'Queen Alia International', 'AMM', 'JO', 'Asia/Amman', NOW(), NOW()),
('BEY', 'Beirut-Rafic Hariri', 'BEY', 'LB', 'Asia/Beirut', NOW(), NOW()),
('TLV', 'Ben Gurion Airport', 'TLV', 'IL', 'Asia/Jerusalem', NOW(), NOW()),
('BGW', 'Baghdad International', 'BGW', 'IQ', 'Asia/Baghdad', NOW(), NOW()),
('EBL', 'Erbil International', 'EBL', 'IQ', 'Asia/Baghdad', NOW(), NOW()),
('BSR', 'Basra International', 'BSR', 'IQ', 'Asia/Baghdad', NOW(), NOW()),
('IKA', 'Tehran Imam Khomeini', 'THR', 'IR', 'Asia/Tehran', NOW(), NOW()),
('THR', 'Mehrabad International', 'THR', 'IR', 'Asia/Tehran', NOW(), NOW()),
('MHD', 'Mashhad International', 'MHD', 'IR', 'Asia/Tehran', NOW(), NOW()),
('SYZ', 'Shiraz International', 'SYZ', 'IR', 'Asia/Tehran', NOW(), NOW()),

-- ========================================
-- 6. MỸ LATIN (Mexico, Trung & Nam Mỹ, Caribe)
-- ========================================
-- Mexico
('MEX', 'Mexico City International', 'MEX', 'MX', 'America/Mexico_City', NOW(), NOW()),
('CUN', 'Cancún International', 'CUN', 'MX', 'America/Cancun', NOW(), NOW()),
('GDL', 'Guadalajara International', 'GDL', 'MX', 'America/Mexico_City', NOW(), NOW()),
('MTY', 'Monterrey International', 'MTY', 'MX', 'America/Monterrey', NOW(), NOW()),
('SJD', 'Los Cabos International', 'SJD', 'MX', 'America/Mazatlan', NOW(), NOW()),
('TIJ', 'Tijuana International', 'TIJ', 'MX', 'America/Tijuana', NOW(), NOW()),
('PVR', 'Licenciado Gustavo Díaz Ordaz', 'PVR', 'MX', 'America/Mexico_City', NOW(), NOW()),
('MID', 'Mérida International', 'MID', 'MX', 'America/Merida', NOW(), NOW()),
('BJX', 'Del Bajío International', 'BJX', 'MX', 'America/Mexico_City', NOW(), NOW()),
-- Brazil
('GRU', 'São Paulo-Guarulhos', 'SAO', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('CGH', 'São Paulo-Congonhas', 'SAO', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('GIG', 'Rio Galeão-Tom Jobim', 'RIO', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('SDU', 'Santos Dumont', 'RIO', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('BSB', 'Brasília International', 'BSB', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('CNF', 'Belo Horizonte International', 'BHZ', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('VCP', 'Viracopos International', 'SAO', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('REC', 'Recife/Guararapes', 'REC', 'BR', 'America/Recife', NOW(), NOW()),
('POA', 'Salgado Filho International', 'POA', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('SSA', 'Salvador International', 'SSA', 'BR', 'America/Bahia', NOW(), NOW()),
('FOR', 'Pinto Martins International', 'FOR', 'BR', 'America/Fortaleza', NOW(), NOW()),
('CWB', 'Afonso Pena International', 'CWB', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
('MAO', 'Eduardo Gomes International', 'MAO', 'BR', 'America/Manaus', NOW(), NOW()),
('FLN', 'Hercílio Luz International', 'FLN', 'BR', 'America/Sao_Paulo', NOW(), NOW()),
-- Colombia
('BOG', 'El Dorado International', 'BOG', 'CO', 'America/Bogota', NOW(), NOW()),
('MDE', 'José María Córdova', 'MDE', 'CO', 'America/Bogota', NOW(), NOW()),
('CTG', 'Rafael Núñez International', 'CTG', 'CO', 'America/Bogota', NOW(), NOW()),
('CLO', 'Alfonso Bonilla Aragón', 'CLO', 'CO', 'America/Bogota', NOW(), NOW()),
('BAQ', 'Ernesto Cortissoz', 'BAQ', 'CO', 'America/Bogota', NOW(), NOW()),
-- Argentina, Chile, Peru
('EZE', 'Ministro Pistarini', 'BUE', 'AR', 'America/Argentina/Buenos_Aires', NOW(), NOW()),
('AEP', 'Aeroparque Jorge Newbery', 'BUE', 'AR', 'America/Argentina/Buenos_Aires', NOW(), NOW()),
('COR', 'Ingeniero Aeronáutico', 'COR', 'AR', 'America/Argentina/Cordoba', NOW(), NOW()),
('MDZ', 'Governor Francisco Gabrielli', 'MDZ', 'AR', 'America/Argentina/Mendoza', NOW(), NOW()),
('BRC', 'San Carlos de Bariloche', 'BRC', 'AR', 'America/Argentina/Salta', NOW(), NOW()),
('SCL', 'Arturo Merino Benítez', 'SCL', 'CL', 'America/Santiago', NOW(), NOW()),
('CJC', 'El Loa Airport', 'CJC', 'CL', 'America/Santiago', NOW(), NOW()),
('PUQ', 'Presidente Carlos Ibáñez', 'PUQ', 'CL', 'America/Punta_Arenas', NOW(), NOW()),
('LIM', 'Jorge Chávez International', 'LIM', 'PE', 'America/Lima', NOW(), NOW()),
('CUZ', 'Alejandro Velasco Astete', 'CUZ', 'PE', 'America/Lima', NOW(), NOW()),
('AQP', 'Rodríguez Ballón', 'AQP', 'PE', 'America/Lima', NOW(), NOW()),
-- Nam Mỹ Khác
('UIO', 'Mariscal Sucre International', 'UIO', 'EC', 'America/Guayaquil', NOW(), NOW()),
('GYE', 'José Joaquín de Olmedo', 'GYE', 'EC', 'America/Guayaquil', NOW(), NOW()),
('CCS', 'Simón Bolívar International', 'CCS', 'VE', 'America/Caracas', NOW(), NOW()),
('MAR', 'La Chinita International', 'MAR', 'VE', 'America/Caracas', NOW(), NOW()),
('LPB', 'El Alto International', 'LPB', 'BO', 'America/La_Paz', NOW(), NOW()),
('VVI', 'Viru Viru International', 'VVI', 'BO', 'America/La_Paz', NOW(), NOW()),
('MVD', 'Carrasco International', 'MVD', 'UY', 'America/Montevideo', NOW(), NOW()),
('ASU', 'Silvio Pettirossi International', 'ASU', 'PY', 'America/Asuncion', NOW(), NOW()),
-- Trung Mỹ
('PTY', 'Tocumen International', 'PTY', 'PA', 'America/Panama', NOW(), NOW()),
('SJO', 'Juan Santamaría International', 'SJO', 'CR', 'America/Costa_Rica', NOW(), NOW()),
('LIR', 'Guanacaste Airport', 'LIR', 'CR', 'America/Costa_Rica', NOW(), NOW()),
('SAL', 'El Salvador International', 'SAL', 'SV', 'America/El_Salvador', NOW(), NOW()),
('GUA', 'La Aurora International', 'GUA', 'GT', 'America/Guatemala', NOW(), NOW()),
('SAP', 'Ramón Villeda Morales', 'SAP', 'HN', 'America/Tegucigalpa', NOW(), NOW()),
('MGA', 'Augusto C. Sandino', 'MGA', 'NI', 'America/Managua', NOW(), NOW()),
('BZE', 'Philip S. W. Goldson', 'BZE', 'BZ', 'America/Belize', NOW(), NOW()),
-- Caribe
('PUJ', 'Punta Cana International', 'PUJ', 'DO', 'America/Santo_Domingo', NOW(), NOW()),
('SDQ', 'Las Américas International', 'SDQ', 'DO', 'America/Santo_Domingo', NOW(), NOW()),
('SJU', 'Luis Muñoz Marín', 'SJU', 'PR', 'America/Puerto_Rico', NOW(), NOW()),
('HAV', 'José Martí International', 'HAV', 'CU', 'America/Havana', NOW(), NOW()),
('MBJ', 'Sangster International', 'MBJ', 'JM', 'America/Jamaica', NOW(), NOW()),
('KIN', 'Norman Manley International', 'KIN', 'JM', 'America/Jamaica', NOW(), NOW()),
('NAS', 'Lynden Pindling International', 'NAS', 'BS', 'America/Nassau', NOW(), NOW()),
('AUA', 'Queen Beatrix International', 'AUA', 'AW', 'America/Aruba', NOW(), NOW()),
('CUR', 'Curaçao International', 'CUR', 'CW', 'America/Curacao', NOW(), NOW()),
('BGI', 'Grantley Adams International', 'BGI', 'BB', 'America/Barbados', NOW(), NOW()),
('POS', 'Piarco International', 'POS', 'TT', 'America/Port_of_Spain', NOW(), NOW()),

-- ========================================
-- 7. CHÂU PHI
-- ========================================
-- Bắc Phi & Nam Phi
('JNB', 'O. R. Tambo International', 'JNB', 'ZA', 'Africa/Johannesburg', NOW(), NOW()),
('CPT', 'Cape Town International', 'CPT', 'ZA', 'Africa/Johannesburg', NOW(), NOW()),
('DUR', 'King Shaka International', 'DUR', 'ZA', 'Africa/Johannesburg', NOW(), NOW()),
('HLA', 'Lanseria International', 'HLA', 'ZA', 'Africa/Johannesburg', NOW(), NOW()),
('PLZ', 'Chief Dawid Stuurman', 'PLZ', 'ZA', 'Africa/Johannesburg', NOW(), NOW()),
('CAI', 'Cairo International', 'CAI', 'EG', 'Africa/Cairo', NOW(), NOW()),
('HRG', 'Hurghada International', 'HRG', 'EG', 'Africa/Cairo', NOW(), NOW()),
('SSH', 'Sharm El Sheikh International', 'SSH', 'EG', 'Africa/Cairo', NOW(), NOW()),
('HBE', 'Borg El Arab', 'ALY', 'EG', 'Africa/Cairo', NOW(), NOW()),
('LXR', 'Luxor International', 'LXR', 'EG', 'Africa/Cairo', NOW(), NOW()),
('CMN', 'Mohammed V International', 'CAS', 'MA', 'Africa/Casablanca', NOW(), NOW()),
('RAK', 'Marrakesh Menara', 'RAK', 'MA', 'Africa/Casablanca', NOW(), NOW()),
('AGA', 'Agadir–Al Massira', 'AGA', 'MA', 'Africa/Casablanca', NOW(), NOW()),
('ALG', 'Houari Boumediene', 'ALG', 'DZ', 'Africa/Algiers', NOW(), NOW()),
('ORN', 'Oran Es Sénia', 'ORN', 'DZ', 'Africa/Algiers', NOW(), NOW()),
('TUN', 'Tunis-Carthage International', 'TUN', 'TN', 'Africa/Tunis', NOW(), NOW()),
('NBE', 'Enfidha-Hammamet', 'NBE', 'TN', 'Africa/Tunis', NOW(), NOW()),
('DJE', 'Djerba-Zarzis International', 'DJE', 'TN', 'Africa/Tunis', NOW(), NOW()),
-- Đông Phi
('ADD', 'Addis Ababa Bole', 'ADD', 'ET', 'Africa/Addis_Ababa', NOW(), NOW()),
('NBO', 'Jomo Kenyatta International', 'NBO', 'KE', 'Africa/Nairobi', NOW(), NOW()),
('MBA', 'Moi International', 'MBA', 'KE', 'Africa/Nairobi', NOW(), NOW()),
('EBB', 'Entebbe International', 'EBB', 'UG', 'Africa/Kampala', NOW(), NOW()),
('DAR', 'Julius Nyerere International', 'DAR', 'TZ', 'Africa/Dar_es_Salaam', NOW(), NOW()),
('ZNZ', 'Abeid Amani Karume', 'ZNZ', 'TZ', 'Africa/Dar_es_Salaam', NOW(), NOW()),
('KGL', 'Kigali International', 'KGL', 'RW', 'Africa/Kigali', NOW(), NOW()),
('JIB', 'Djibouti-Ambouli International', 'JIB', 'DJ', 'Africa/Djibouti', NOW(), NOW()),
-- Tây & Trung Phi
('LOS', 'Murtala Muhammed', 'LOS', 'NG', 'Africa/Lagos', NOW(), NOW()),
('ABV', 'Nnamdi Azikiwe', 'ABV', 'NG', 'Africa/Lagos', NOW(), NOW()),
('PHC', 'Port Harcourt International', 'PHC', 'NG', 'Africa/Lagos', NOW(), NOW()),
('DKR', 'Blaise Diagne International', 'DKR', 'SN', 'Africa/Dakar', NOW(), NOW()),
('ACC', 'Kotoka International', 'ACC', 'GH', 'Africa/Accra', NOW(), NOW()),
('ABJ', 'Félix-Houphouët-Boigny', 'ABJ', 'CI', 'Africa/Abidjan', NOW(), NOW()),
('LFW', 'Gnassingbé Eyadéma', 'LFW', 'TG', 'Africa/Lome', NOW(), NOW()),
('DLA', 'Douala International', 'DLA', 'CM', 'Africa/Douala', NOW(), NOW()),
('NSI', 'Yaoundé Nsimalen', 'NSI', 'CM', 'Africa/Douala', NOW(), NOW()),
('FIH', 'N''djili Airport', 'FIH', 'CD', 'Africa/Kinshasa', NOW(), NOW()),
('LAD', 'Quatro de Fevereiro', 'LAD', 'AO', 'Africa/Luanda', NOW(), NOW()),
-- Đảo Ấn Độ Dương
('MRU', 'Sir Seewoosagur Ramgoolam', 'MRU', 'MU', 'Indian/Mauritius', NOW(), NOW()),
('SEZ', 'Seychelles International', 'SEZ', 'SC', 'Indian/Mahe', NOW(), NOW()),
('RUN', 'Roland Garros', 'RUN', 'RE', 'Indian/Reunion', NOW(), NOW()),
('TNR', 'Ivato International', 'TNR', 'MG', 'Indian/Antananarivo', NOW(), NOW()),

-- ========================================
-- 8. CHÂU ÚC & ĐẠI DƯƠNG
-- ========================================
-- Úc (Australia)
('SYD', 'Sydney Kingsford Smith', 'SYD', 'AU', 'Australia/Sydney', NOW(), NOW()),
('MEL', 'Melbourne Airport', 'MEL', 'AU', 'Australia/Melbourne', NOW(), NOW()),
('BNE', 'Brisbane Airport', 'BNE', 'AU', 'Australia/Brisbane', NOW(), NOW()),
('PER', 'Perth Airport', 'PER', 'AU', 'Australia/Perth', NOW(), NOW()),
('ADL', 'Adelaide Airport', 'ADL', 'AU', 'Australia/Adelaide', NOW(), NOW()),
('OOL', 'Gold Coast Airport', 'OOL', 'AU', 'Australia/Brisbane', NOW(), NOW()),
('CBR', 'Canberra Airport', 'CBR', 'AU', 'Australia/Sydney', NOW(), NOW()),
('CNS', 'Cairns Airport', 'CNS', 'AU', 'Australia/Brisbane', NOW(), NOW()),
('DRW', 'Darwin International', 'DRW', 'AU', 'Australia/Darwin', NOW(), NOW()),
('HBA', 'Hobart Airport', 'HBA', 'AU', 'Australia/Hobart', NOW(), NOW()),
('LST', 'Launceston Airport', 'LST', 'AU', 'Australia/Hobart', NOW(), NOW()),
('TSV', 'Townsville Airport', 'TSV', 'AU', 'Australia/Brisbane', NOW(), NOW()),
('MKY', 'Mackay Airport', 'MKY', 'AU', 'Australia/Brisbane', NOW(), NOW()),
('AVV', 'Avalon Airport', 'MEL', 'AU', 'Australia/Melbourne', NOW(), NOW()),
('Ntl', 'Newcastle Airport', 'NTL', 'AU', 'Australia/Sydney', NOW(), NOW()),
-- New Zealand & Đảo Thái Bình Dương
('AKL', 'Auckland Airport', 'AKL', 'NZ', 'Pacific/Auckland', NOW(), NOW()),
('WLG', 'Wellington International', 'WLG', 'NZ', 'Pacific/Auckland', NOW(), NOW()),
('CHC', 'Christchurch International', 'CHC', 'NZ', 'Pacific/Auckland', NOW(), NOW()),
('ZQN', 'Queenstown Airport', 'ZQN', 'NZ', 'Pacific/Auckland', NOW(), NOW()),
('DUN', 'Dunedin Airport', 'DUN', 'NZ', 'Pacific/Auckland', NOW(), NOW()),
('NAN', 'Nadi International', 'NAN', 'FJ', 'Pacific/Fiji', NOW(), NOW()),
('SUV', 'Nausori International', 'SUV', 'FJ', 'Pacific/Fiji', NOW(), NOW()),
('POM', 'Jacksons International', 'POM', 'PG', 'Pacific/Port_Moresby', NOW(), NOW()),
('GUM', 'Antonio B. Won Pat', 'GUM', 'GU', 'Pacific/Guam', NOW(), NOW()),
('SPN', 'Francisco C. Ada/Saipan', 'SPN', 'MP', 'Pacific/Saipan', NOW(), NOW()),
('PPT', 'Fa''a''ā International', 'PPT', 'PF', 'Pacific/Tahiti', NOW(), NOW()),
('NOU', 'La Tontouta International', 'NOU', 'NC', 'Pacific/Noumea', NOW(), NOW()),
('VLI', 'Bauerfield International', 'VLI', 'VU', 'Pacific/Efate', NOW(), NOW()),
('TBU', 'Fua''amotu International', 'TBU', 'TO', 'Pacific/Tongatapu', NOW(), NOW()),
('APW', 'Faleolo International', 'APW', 'WS', 'Pacific/Apia', NOW(), NOW()),
('SIN', 'Changi Airport', 'SIN', 'SG', 'Asia/Singapore', NOW(), NOW())

    ON CONFLICT (code) DO NOTHING;

-- Thêm các ông lớn Hàng không
INSERT INTO airlines (code, name) VALUES
('AA', 'American Airlines'),
('DL', 'Delta Air Lines'),
('UA', 'United Airlines'),
('EK', 'Emirates'),
('QR', 'Qatar Airways'),
('LH', 'Lufthansa'),
('SQ', 'Singapore Airlines')
ON CONFLICT (code) DO NOTHING;